from .person import Person
from .customer import Customer
from .registerUser import RegisterUser
from .spare import Spare
from .maintenance import Maintenance
from .vehicle import Vehicle
from .spareDetails import SpareDetails
from .vehicleImage import VehicleImage
from .provider import Provider
from .arrival import Arrival
from .arrivalDetails import ArrivalDetails
from .establishment import Establishment
from .categorie import Categorie
from .customerVehicle import CustomerVehicle
