# Generated by Django 5.1.7 on 2026-02-04 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id_card', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('mail', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('details', models.CharField(blank=True, max_length=70, null=True)),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('economic_activity', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=50, unique=True)),
                ('tax_added', models.IntegerField(default=0)),
                ('currencyName', models.CharField(max_length=50)),
                ('legalIdentifier', models.CharField(blank=True, max_length=27)),
                ('taxIdentifier', models.CharField(blank=True, max_length=27)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('ubication', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('engine_info', models.CharField(max_length=80)),
                ('distance', models.CharField(max_length=30)),
                ('plate', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(max_length=40)),
                ('transmition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autotaller.person')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('autotaller.person', models.Model),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autotaller.person')),
                ('documentType', models.CharField(max_length=30)),
            ],
            bases=('autotaller.person',),
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('idArrival', models.AutoField(primary_key=True, serialize=False)),
                ('arrivalDate', models.DateField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotaller.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotaller.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('diagnosis', models.CharField(max_length=90)),
                ('cost_job', models.DecimalField(decimal_places=2, max_digits=5)),
                ('task_status', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=30)),
                ('idMaintenance', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_method', models.CharField(max_length=40)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotaller.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('idPhoto', models.AutoField(primary_key=True, serialize=False)),
                ('photoUrl', models.ImageField(upload_to='img/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotaller.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotaller.arrival')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotaller.spare')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spare', 'arrival'), name='unique_spare_arrival')],
            },
        ),
        migrations.CreateModel(
            name='SpareDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotaller.maintenance')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotaller.spare')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spare', 'maintenance'), name='unique_spare_maintenance')],
            },
        ),
        migrations.CreateModel(
            name='CustomerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeDate', models.DateField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotaller.vehicle')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotaller.customer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'vehicle'), name='unique_customer_vehicle')],
            },
        ),
    ]
